blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/ethereum/solidity/issues/new?template=bug_report.md&projects=ethereum/solidity/43&labels=bug+%3Abug%3A
    about: Bug reports about the Solidity Compiler.
  - name: Documentation Issue
    url: https://github.com/ethereum/solidity/issues/new?template=documentation_issue.md&projects=ethereum/solidity/43&labels=documentation+%3Abook%3A
    about: Solidity documentation.
  - name: Feature Request
    url: https://github.com/ethereum/solidity/issues/new?template=feature_request.md&projects=ethereum/solidity/43&labels=feature
    about: Solidity language or infrastructure feature requests.
  - name: Report a security vulnerability
    url: https://github.com/ethereum/solidity/security/policy
    about: Please review our security policy for more details.
