blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability
    url: https://github.com/ethereum/solidity/security/policy
    about: Please review our security policy for more details.
  - name: Initiate a language design or feedback discussion
    url: https://forum.soliditylang.org
    about: Open a thread on the Solidity forum.
